defaults: #points to sub-configs
  - model: deeplabv3plus
  - styles: styles_1.yaml # config for terminal printing. Paper plotting is in Matplotlib stylesheet
  - _self_ # main overrides sub-cfg in case of duplicates


# EXPERIMENT CONFIG
#####################################################################

# NOTE: hydra configs are not passed on to cfg and don't need schema
hydra:
  run:
    dir: ./experiments/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} #change to onedrive folder
  sweep:
    dir: ./experiments/hydra_outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

experiment:
  seed: 42
  train_fraction: 0.8
  early_stopping_patience: 10
  dataset_train: synthetic_real
  dataset_test: synthetic_box
  crossvalidation: false
  matplotlib_config_path: ./scripts/config/figures_styles.mplstyle

mlflow:
  path: ./experiments/mlruns
  experiment_name: null # is set when calling scripts

dataset:
  path_raw: .
