defaults:
- model: unet
- _self_
path_project: C:\Users\KYC\OneDrive - NGI\Documents\PhD\Paper - Synthetic rock joint
  generation for ML
matplotlib_config_path: ./scripts/config/figures_styles.mplstyle
hydra:
  run:
    dir: ${path_project}/experiments/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${path_project}/experiments/hydra_outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
azure_ml:
  compute_name: Standard-NC6s-v3
  experiment_name: rock-segmentation
  environment_name: rock-segmentation-env-curated-py310
  environment_version: '2'
  use_new_version: true
  use_curated_env: true
  curated_env_name: azureml://registries/azureml/environments/acpt-pytorch-2.2-cuda12.1/labels/latest
  base_docker_image: mcr.microsoft.com/azureml/curated/acpt-pytorch-2.2-cuda12.1:37
azure_data_assets:
  command: register-base-datasets
  asset_name: null
  version1: null
  version2: null
  output_dir: outputs/azure_data_assets/${now:%Y-%m-%d_%H-%M-%S}
experiment:
  seed: 42
  log_mlflow: true
  compare_metric: loss
  num_workers: 4
  train_fraction: 0.8
  val_fraction: 0.1
  test_fraction: 0.1
  early_stopping_patience: 3
  early_stopping_delta: 0.005
  optional_transforms: false
  overfit_check: false
  sanity_check_num_batches: null
  quality_control_data: false
  crossvalidation: false
  path_example_images: ${path_project}/experiments/example_images
  download_outputs: false
  smoke_test: false
  smoke_test_use_cuda: false
  smoke_test_minimal: false
  experiment_strategy: verification_box
  dataset_strategies:
    verification_box:
      train_datasets:
      - synthetic_box
      test_datasets:
      - synthetic_box
    verification_dfn:
      train_datasets:
      - synthetic_dfn
      test_datasets:
      - synthetic_dfn
    main_objective_dfn_rock_slope:
      train_datasets:
      - synthetic_dfn
      test_datasets:
      - real_world_rock_slope
    main_objective_dfn_box:
      train_datasets:
      - synthetic_dfn
      test_datasets:
      - real_world_box
    main_objective_box_rock_slope:
      train_datasets:
      - synthetic_box
      test_datasets:
      - real_world_rock_slope
    main_objective_box_box:
      train_datasets:
      - synthetic_box
      test_datasets:
      - real_world_box
    dataset_size_test:
      train_datasets:
      - synthetic_dfn
      test_datasets:
      - real_world_rock_slope
    semi_supervised_learning:
      train_datasets:
      - real_world_rock_slope
      test_datasets:
      - real_world_rock_slope
    one_shot_segmentation:
      train_datasets:
      - real_world_rock_slope
      test_datasets: []
dataset:
  path_images: ${path_project}/Data/rockmass
  path_raw_mask_labels: ${path_project}/Data/label/raw
  path_processed_mask_labels: ${path_project}/Data/label/binary
  crop_size: 768
  prefixes:
    synthetic_dfn:
    - FracMan
    synthetic_box:
    - Benchmark
    real_world_box:
    - Box
    real_world_rock_slope:
    - Larvik
    - Rv4
tensorboard:
  path: ./experiments/tensorboard_logs
mlflow:
  path: ${path_project}/experiments/mlruns
  experiment_name: null
  save_model: true
optuna:
  n_trials: 5
  path_results: experiments/hyperparameters
