# Optimized UNet configuration for Box strategy
# Based on hyperparameter optimization for main_objective_box_box experiment
name: unet_box_optimised
num_epochs: 50
batch_size: 4
learning_rate: 0.00030906469407023527
scheduler:
  patience: 7
  gamma: 0.11197940328365186
params:
  encoder_name: 'efficientnet-b0'
  encoder_weights: imagenet # use `imagenet` pre-trained weights for encoder initialization
  in_channels: 3            # model input channels (1 for gray-scale images, 3 for RGB, etc.)
  classes: 1                # model output channels (number of classes in your dataset)
  encoder_depth: 5
  decoder_use_batchnorm: false
  decoder_channels: [256, 128, 64, 32, 16]
  decoder_attention_type: null
  activation: null
  aux_params: null
